# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!


target 'GlobalMessageService' do
    pod 'Google/CloudMessaging'#, '~> 1.1.3'
    pod 'Alamofire', '~> 3.1'
    pod 'XCGLogger', '~> 3.2'
    pod 'JSQMessagesViewController', '~> 7.2'
    pod 'DZNEmptyDataSet', '~> 1.7.3'
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end

#target 'GlobalMessageServiceTests' do

#end

