sudo: required
lannguage: objective-c
osx_image: xcode7.2
xcode_workspace: GlobalMessageService.xcworkspace
xcode_scheme: GlobalMessageService
xcode_sdk: iphonesimulator9.2

cache: cocoapods
podfile: ./GlobalMessageService/Podfile

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
