language: objective-c
rvm: 2.2.3
osx_image: xcode7.3
xcode_workspace: ./GlobalMessageService/GlobalMessageService.xcworkspace
xcode_scheme: GlobalMessageService
xcode_sdk: iphonesimulator9.3

cache: 
  - bundler
  - cocoapods

podfile: ./GlobalMessageService/Podfile
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=./GlobalMessageService/GlobalMessageService.xcworkspace
    - IOS_FRAMEWORK_SCHEME="GlobalMessageService"
    - IOS_SDK=iphonesimulator9.3
  matrix:
    - DESTINATION="OS=8.0,name=iPhone 4S"      SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" POD_LINT="NO" RUN_TESTS="YES"
    - DESTINATION="OS=9.2,name=iPhone 5S"      SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" POD_LINT="NO" RUN_TESTS="YES"
    - DESTINATION="OS=9.3,name=iPhone 6S Plus" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" POD_LINT="NO" RUN_TESTS="YES"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - git submodule update --init --recursive
  - xcodebuild -version
  - xcodebuild -showsdks
  
  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
  
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod repo update master;
      pod lib lint;
    fi
